name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    
    - name: Docker Login - Azure ACR
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.APP_DOCKER_REGISTRY }}
        username: ${{ secrets.APP_DOCKER_USERNAME }}
        password: ${{ secrets.APP_DOCKER_PASSWORD }}

    - name: Build e Push no Azure ACR
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.APP_DOCKER_REGISTRY }}/${{ secrets.APP_DOCKER_IMAGE }}:latest
        docker push ${{ secrets.APP_DOCKER_REGISTRY }}/${{ secrets.APP_DOCKER_IMAGE }}:latest
